name: Node.js CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET: ${{ secrets.SECRET }}
      SECRET_HASH_KEY: ${{ secrets.SECRET_HASH_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.11.0"
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build the project (se houver um script "build")
      run: npm run build --if-present

    - name: Run Tests
      run: npm test
